### ISSUE TITLE
Missing data for Ghana

### ISSUE THREAD

**Issue by koapeadu** [SimonCropp/CountryData#398]
Please include country data for Ghana.
I get the error "Could not find data for GH" when I try `CountryLoader.LoadLocationData("GH")`.

I'm using package version 3.69.0 and dotnet version 5.

**Comment by SimonCropp** [comment]
the source of this data is from https://www.geonames.org/. specifically http://download.geonames.org/export/zip/allCountries.zip. and that does not seem to contain information for ghana
