### ISSUE TITLE
Targeting .NET Standard 2.0

### ISSUE THREAD

**Issue by tgourley** [SimonCropp/CountryData#541]
#### Is the feature request related to a problem

I am working on a project that would like to include internationalization which requires a standard set of countries and states.  This project fits that, but I have a problem related to the targeted SDK.  This internationalization is for several projects using .NET Framework 4.8, .NET 6, .NET 8 projects, and .NET Standard 2.1.

Since this package targets .NET 8, I am unable to use it in a .NET Framework 4.8 or .NET Standard 2.1 projects.

#### Describe the solution

Would it be viable to convert this project/library to target the .NET Standard 2.0 SDK?  This would give it maximum compatibility with all the mentioned frameworks above.

I have checked out the `CountryData` repo and made the change and it compiles and runs successfully in my local test projects as a .NET Standard 2.0 library.  I have manually added it to .NET Standard 2.1 and .NET Framework 4.8 projects, and the library is working as expected and I can pull country information.

**Comment by SimonCropp** [comment]
what is your requirement for .NET 6? From my experience it is not much effort to move to net8

**Comment by tgourley** [comment]
My requirement is for .NET Framework 4.8.  As of now the highest it supports is .NET Standard 2.0 (and I don't expect it to add support for 2.1.)

**Comment by SimonCropp** [comment]
i am not a fan of targeting .NET Standard. it implies to consumers that a lib supports many unsupported runtimes. for example .NET Standard 2.1implies support for .NET Core 3.0.

i am reluctant to add net6 support at this point, given it is out of support in November

happy to accept a PR that adds net48 support

> when pulling the states of Mexico the state codes are just numbers instead of the standard state code. 

can you give me a unit test that illustrates the problem?

**Comment by tgourley** [comment]
Here is the test:

```
[Fact]
public void MexicoStateNotNumber()
{
    var state = CountryDataSet.Mexico().State();
    var isInt = int.TryParse(state.Code, out var code);
    Assert.False(isInt);
}
```

All the state codes for Mexico are numbers.
![image](https://github.com/user-attachments/assets/121da092-9239-4203-887b-1e231ef75c06)

I know this is likely due to the GeoNames data and not your library.

There are two and three digit codes for the states as described here:  https://en.wikipedia.org/wiki/Template:Mexico_State-Abbreviation_Codes

**Comment by tgourley** [comment]
Unfortunately, there appears to be some libraries that are not .NET 4.8 compatible.
![image](https://github.com/user-attachments/assets/b580976b-cb9b-4c81-be05-297a80825020)

**Comment by SimonCropp** [comment]
so yes it looks like the mexico state codes is an underlying issue in GeoNames

do you still want me to go to the effort of supporting net48

**Comment by tgourley** [comment]
I don’t think it will be necessary at this point as we went to another library that has the correct Mexico data.  Thanks.
